description: "A set of standard steps which we use for projects at Table XI"
version: 2.1
executors:
  default_executor:
    # The working directory is important, so that we
    # install/cache everything relative to that location
    working_directory: ~/tmp
    docker:
      - image: circleci/ruby:2.5-node
        environment:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: ubuntu
          # Bundle paths are necessary so that the gems are installed within the workspace
          # otherwise, they are installed in /usr/local
          BUNDLE_PATH: ~/tmp/vendor/bundle
          BUNDLE_APP_CONFIG: ~/tmp/vendor/bundle
      - image: circleci/postgres:9-alpine
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_PASSWORD: ""

commands:
  wait_for_other_builds:
    description: "Ensure no earlier numbered job (of this branch) is running"
    steps:
      - run:
          name: Wait for other builds to finish before running
          command: |
            mkdir -p ~/bin
            wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 -O ~/bin/jq
            wget https://raw.githubusercontent.com/bellkev/circle-lock-test/02d45b47f8bf8e6009aa7fca9e9a7257a77a0404/do-exclusively -O ~/bin/do-exclusively
            chmod +x ~/bin/jq ~/bin/do-exclusively
            export PATH=$PATH:$HOME/bin
            do-exclusively --branch $CIRCLE_BRANCH echo "We have an exclusive lock on the current branch"
  wait_for_db:
    description: "Wait for the database to be ready to accept connections"
    parameters:
      executor:
        type: executor
        default: default_executor
      mysql_db_type:
        type: boolean
        default: false
    steps:
      - when:
          condition: << parameters.mysql_db_type >>
          steps:
            - run: dockerize -wait tcp://localhost:3306 -timeout 2m
      - unless:
          condition: << parameters.mysql_db_type >>
          steps:
            - run: dockerize -wait tcp://localhost:5432 -timeout 2m
  load_db_schema:
    description: "Load the database schema, no matter the db type"
    parameters:
      executor:
        type: executor
        default: default_executor
      mysql_db_type:
        type: boolean
        default: false
    steps:
      # Install the database library, so that we can run rake db:structure:load
      - when:
          condition: << parameters.mysql_db_type >>
          steps:
            - run: if [ -e db/structure.sql ]; then sudo apt-get install -y mysql-client; fi
      - unless:
          condition: << parameters.mysql_db_type >>
          steps:
            - run: if [ -e db/structure.sql ]; then sudo apt-get install -y postgresql-client; fi

      - run: if [ -e db/schema.rb ]; then bundle exec rake db:schema:load; fi
      - run: if [ -e db/structure.sql ]; then bundle exec rake db:structure:load; fi
  prepare_database:
    description: "Wait for DB, the create and Load the database schema"
    parameters:
      executor:
        type: executor
        default: default_executor
      mysql_db_type:
        type: boolean
        default: false
    steps:
      - wait_for_db:
          mysql_db_type: << parameters.mysql_db_type >>
          executor: << parameters.executor >>

      - run: bundle exec rake db:create

      - load_db_schema:
          mysql_db_type: << parameters.mysql_db_type >>
          executor: << parameters.executor >>

jobs:
  check_db_schema:
    description: check to ensure that we can migrate from scratch and end up with the schema.rb
    parameters:
      executor:
        type: executor
        default: default_executor
      mysql_db_type:
        type: boolean
        default: false
    executor: << parameters.executor >>
    steps:
      - attach_workspace:
          at: ~/tmp
      - wait_for_db:
          mysql_db_type: << parameters.mysql_db_type >>
          executor: << parameters.executor >>
      - run: bundle exec rake db:drop db:create db:migrate RAILS_ENV=test
      # # check that the schema.rb/structure.sql is the same result
      - run: if [ -e db/schema.rb ]; then git diff --exit-code db/schema.rb; fi
      - run: if [ -e db/structure.sql ]; then git diff --exit-code db/structure.sql; fi

  rubocop:
    description: run the rubocop command
    parameters:
      executor:
        type: executor
        default: default_executor

    executor: << parameters.executor >>
    steps:
      - attach_workspace:
          at: ~/tmp
      - run: bundle exec rubocop --config .rubocop.yml

  bundle_audit:
    description: run the bundle-audit command
    parameters:
      executor:
        type: executor
        default: default_executor

    executor: << parameters.executor >>
    steps:
      - attach_workspace:
          at: ~/tmp
      - run: bundle exec bundle-audit

  haml_lint:
    description: run the haml-lint command
    parameters:
      executor:
        type: executor
        default: default_executor

    executor: << parameters.executor >>
    steps:
      - attach_workspace:
          at: ~/tmp
      - run: bundle exec haml-lint

  rspec:
    description: Run Rspec after waiting for db and loading schema
    parameters:
      executor:
        type: executor
        default: default_executor
      mysql_db_type:
        type: boolean
        default: false
      parallelism:
        type: integer
        default: 1
      report_coverage:
        type: boolean
        default: false
    executor: << parameters.executor >>
    parallelism: << parameters.parallelism >>
    steps:
      - attach_workspace:
          at: ~/tmp
      - prepare_database:
          mysql_db_type: << parameters.mysql_db_type >>
          executor: << parameters.executor >>

      # Run rspec in parallel
      - run:
          shell: /bin/bash -eo pipefail -O globstar
          name: rspec
          command: |
            bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out test_results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Save test results for timing analysis
      - store_test_results:
          path: test_results

      - when:
          condition: << parameters.report_coverage >>
          steps:
            - store_artifacts:
               path: coverage/.resultset.json
               prefix: coverage

            - deploy:
                name: Merge and copy coverage data
                command: bundle exec report_coverage --branch develop
  teaspoon:
    description: Run teaspoon after waiting for db and loading schema
    parameters:
      executor:
        type: executor
        default: default_executor
      mysql_db_type:
        type: boolean
        default: false
    executor: << parameters.executor >>
    steps:
      - attach_workspace:
          at: ~/tmp

      - prepare_database:
          mysql_db_type: << parameters.mysql_db_type >>
          executor: << parameters.executor >>

      - run: mkdir -p ~/teaspoon
      - run:
          command: |
            bundle exec teaspoon \
            --suppress-log \
            --format junit > ~/teaspoon/teaspoon.xml
